#
# This file generates the sidebar/toctree for all Jsk_Docs projects and should
# be copied to each project when it is updated
#
# COPIED FROM https://github.com/robotpy/robotpy-docs

import os


def write_if_changed(fname, contents):

    try:
        with open(fname, "r") as fp:
            old_contents = fp.read()
    except:
        old_contents = ""

    if old_contents != contents:
        with open(fname, "w") as fp:
            fp.write(contents)


def generate_sidebar(conf, conf_api):

    # determine 'latest' or 'stable'
    # if not conf.do_gen:
    do_gen = os.environ.get("SIDEBAR", None) == "1" or conf["on_rtd"]
    version = conf["rtd_version"]

    lines = ["", ".. DO NOT MODIFY! THIS PAGE IS AUTOGENERATED!", ""]

    def toctree(name):
        lines.extend(
            [".. toctree::", "    :caption: %s" % name, "    :maxdepth: 2", ""]
        )

    def endl():
        lines.append("")

    def write(desc, link):
        if conf_api == "jsk_docs":
            args = desc, link
        elif not do_gen:
            return
        else:
            args = (
                desc,
                "https://jsk_docs.readthedocs.io/en/%s/%s.html" % (version, link),
            )

        lines.append("    %s <%s>" % args)

    def write_api(project, desc):
        if project != conf_api:
            if do_gen:
                args = desc, project
                lines.append(
                    "    %s API <https://jsk_docs.readthedocs.io/projects/%s/>"
                    % args
                )
        else:
            lines.append("    %s API <api>" % desc)

    #
    # Specify the sidebar contents here
    #

    toctree("API Reference")
    for subproject in ['jsk_common', 'jsk_roseus', 'jsk_recognition', 'jsk_visualization', 'jsk_planning', 'jsk_control', 'jsk_smart_apps', 'jsk_travis', 'jsk_robot', 'jsk_demos',
                       'hrpsys-base', 'rtmros_common', 'rtmros_tutorials', 'rtmros_choreonoid', 'rtmros_gazebo', 'rtmros_hironx', 'jsk_apc']:
        write_api(subproject, subproject)
    endl()

    write_if_changed("_sidebar.rst.inc", "\n".join(lines))
